<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\ProductStatus;
use App\Enums\SaleType;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Disable foreign key checks to allow truncation
        \Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();
        Product::truncate();
        \Illuminate\Support\Facades\Schema::enableForeignKeyConstraints();

        $products = $this->getProductsData();

        foreach ($products as $productData) {
            $category = Category::where('name', $productData['category'])->first();

            // Try to find sub-category if main category not found, or just fuzzy match
            if (!$category) {
                // Try finding by like if exact match fails, or skip
                 $category = Category::where('name', 'like', '%' . $productData['category'] . '%')->first();
            }

            if (!$category) {
                continue;
            }

            Product::create([
                'category_id' => $category->id,
                'sku' => $productData['sku'],
                'name' => $productData['name'],
                'slug' => Str::slug($productData['name']) . '-' . Str::random(5),
                'short_description' => $productData['short_description'],
                'description' => $productData['description'],
                'price' => $productData['price'],
                'compare_price' => $productData['compare_price'] ?? null,
                'cost_price' => (int) ($productData['price'] * 0.6),
                'stock_quantity' => $productData['stock'],
                'low_stock_threshold' => 5,
                'track_stock' => true,
                'material' => $productData['material'],
                'color' => $productData['color'],
                'weight' => $productData['weight'],
                'length' => $productData['dimensions']['length'],
                'width' => $productData['dimensions']['width'],
                'height' => $productData['dimensions']['height'],
                'specifications' => $productData['specifications'],
                'status' => ProductStatus::ACTIVE,
                'sale_type' => $productData['sale_type'] ?? SaleType::REGULAR,
                'is_featured' => $productData['is_featured'] ?? false,
                'is_new_arrival' => $productData['is_new_arrival'] ?? false,
                'discount_percentage' => $productData['discount'] ?? null,
                'discount_starts_at' => isset($productData['discount']) ? now() : null,
                'discount_ends_at' => isset($productData['discount']) ? now()->addDays(30) : null,
                'meta_title' => $productData['name'] . ' - Toko Furniture',
                'meta_description' => $productData['short_description'],
            ]);
        }
    }

    /** @return array<int, array<string, mixed>> */
    private function getProductsData(): array
    {
        return [
            // SOFA & BENCH
            [
                'sku' => 'SFA-001',
                'name' => 'Sofa Minimalis 3 Seater Grey',
                'category' => 'Sofa & Bench',
                'short_description' => 'Sofa minimalis modern untuk 3 orang dengan bahan kain premium',
                'description' => 'Sofa tri-seater dengan desain skandinavia yang minimalis. Menggunakan rangka kayu solid dan busa high-density yang tidak mudah kempes. Lapisan kain fabric premium yang lembut dan mudah dibersihkan.',
                'price' => 4500000,
                'compare_price' => 5500000,
                'stock' => 15,
                'material' => 'Kayu Solid, Fabric, Busa HD',
                'color' => 'Abu-abu',
                'weight' => 45.0,
                'dimensions' => ['length' => 210, 'width' => 85, 'height' => 80],
                'specifications' => ['garansi' => '2 Tahun Rangka', 'kapasitas' => '3 Orang', 'kain' => 'Canvas Premium'],
                'is_featured' => true,
                'is_new_arrival' => true,
                'discount' => 15,
                'sale_type' => SaleType::HOT_SALE,
            ],
            [
                'sku' => 'SFA-L-002',
                'name' => 'Sofa L-Shape Corner Modern',
                'category' => 'Sofa & Bench',
                'short_description' => 'Sofa sudut bentuk L yang luas dan nyaman',
                'description' => 'Sofa corner L-shape yang memaksimalkan sudut ruang tamu Anda. Cocok untuk berkumpul bersama keluarga besar. Dilengkapi bantal peluk.',
                'price' => 7800000,
                'compare_price' => 8900000,
                'stock' => 5,
                'material' => 'Kayu Mahoni, Velvet',
                'color' => 'Navy Blue',
                'weight' => 65.0,
                'dimensions' => ['length' => 240, 'width' => 160, 'height' => 85],
                'specifications' => ['garansi' => '2 Tahun', 'orientasi' => 'Kanan/Kiri Flexible'],
                'is_featured' => true,
            ],
            [
                'sku' => 'BNC-001',
                'name' => 'Bench Teak Outdoor',
                'category' => 'Sofa & Bench',
                'short_description' => 'Bangku taman kayu jati solid untuk outdoor',
                'description' => 'Bangku taman elegan dari kayu jati solid yang tahan cuaca. Cocok untuk teras, taman, atau area outdoor lainnya.',
                'price' => 3200000,
                'stock' => 10,
                'material' => 'Kayu Jati Solid',
                'color' => 'Natural Teak',
                'weight' => 35.0,
                'dimensions' => ['length' => 150, 'width' => 50, 'height' => 90],
                'specifications' => ['garansi' => '3 Tahun', 'kapasitas' => '3 Orang'],
                'is_featured' => true,
            ],

            // COFFEE TABLE
            [
                'sku' => 'CFT-001',
                'name' => 'Coffee Table Industrial',
                'category' => 'Coffee Table',
                'short_description' => 'Meja kopi bergaya industrial dengan kaki besi',
                'description' => 'Meja kopi (coffee table) dengan perpaduan kayu jati solid dan kaki besi hollow hitam. Tampilan maskulin dan kokoh untuk ruang tamu modern industrial.',
                'price' => 1250000,
                'stock' => 20,
                'material' => 'Kayu Jati, Besi Hollow',
                'color' => 'Natural Wood & Black',
                'weight' => 12.0,
                'dimensions' => ['length' => 100, 'width' => 60, 'height' => 45],
                'specifications' => ['finishing' => 'Matte', 'ketebalan_top' => '3cm'],
            ],
            [
                'sku' => 'CFT-002',
                'name' => 'Round Coffee Table Marble',
                'category' => 'Coffee Table',
                'short_description' => 'Meja kopi bundar dengan top marmer',
                'description' => 'Meja kopi elegan dengan permukaan marmer alami dan kaki besi gold. Memberikan kesan mewah untuk ruang tamu Anda.',
                'price' => 2850000,
                'stock' => 8,
                'material' => 'Marmer, Besi Gold',
                'color' => 'White Marble & Gold',
                'weight' => 25.0,
                'dimensions' => ['length' => 80, 'width' => 80, 'height' => 45],
                'specifications' => ['finishing' => 'Polished', 'tipe_marmer' => 'Carrara'],
                'is_featured' => true,
            ],

            // BED FRAMES
            [
                'sku' => 'BED-001',
                'name' => 'Bed Frame King Size Jati',
                'category' => 'Bed Frames',
                'short_description' => 'Rangka tempat tidur king size kayu jati solid',
                'description' => 'Bed frame king size (180x200) dari kayu jati pilihan. Desain headboard klasik modern dengan ukiran minimalis. Sangat kokoh dan awet puluhan tahun.',
                'price' => 8500000,
                'stock' => 8,
                'material' => 'Kayu Jati Grade A',
                'color' => 'Walnut Brown',
                'weight' => 120.0,
                'dimensions' => ['length' => 210, 'width' => 190, 'height' => 110],
                'specifications' => ['garansi' => '5 Tahun', 'ukuran_kasur' => '180x200 cm', 'sistem_rakit' => 'Knock-down'],
                'is_featured' => true,
            ],
            [
                'sku' => 'BED-002',
                'name' => 'Bed Frame Queen Minimalist',
                'category' => 'Bed Frames',
                'short_description' => 'Rangka tempat tidur queen size minimalis',
                'description' => 'Bed frame queen size (160x200) dengan desain minimalis skandinavian. Cocok untuk kamar tidur modern.',
                'price' => 5500000,
                'stock' => 12,
                'material' => 'Kayu Mahoni',
                'color' => 'Natural Oak',
                'weight' => 85.0,
                'dimensions' => ['length' => 200, 'width' => 170, 'height' => 90],
                'specifications' => ['garansi' => '3 Tahun', 'ukuran_kasur' => '160x200 cm'],
            ],

            // DINING TABLE
            [
                'sku' => 'DTB-001',
                'name' => 'Dining Table 6 Seater Scandi',
                'category' => 'Dining Table',
                'short_description' => 'Meja makan keluarga 6 kursi desain scandinavian',
                'description' => 'Meja makan 6 orang dengan desain skandinavian yang elegan. Kaki kayu solid yang estetik dan top table yang kokoh.',
                'price' => 4500000,
                'compare_price' => 5200000,
                'stock' => 12,
                'material' => 'Kayu Karet (Rubberwood)',
                'color' => 'Natural Wood',
                'weight' => 55.0,
                'dimensions' => ['length' => 160, 'width' => 90, 'height' => 75],
                'specifications' => ['finishing' => 'Nitrocellulose', 'kapasitas' => '6 Orang'],
                'is_featured' => true,
                'discount' => 10,
                'sale_type' => SaleType::STOCK_SALE,
            ],
            [
                'sku' => 'DTB-002',
                'name' => 'Dining Table Extendable 8 Seater',
                'category' => 'Dining Table',
                'short_description' => 'Meja makan extendable untuk 8 orang',
                'description' => 'Meja makan yang bisa diperpanjang dari 6 menjadi 8 orang. Sangat praktis untuk acara keluarga besar.',
                'price' => 7200000,
                'stock' => 6,
                'material' => 'Kayu Jati',
                'color' => 'Dark Brown',
                'weight' => 75.0,
                'dimensions' => ['length' => 200, 'width' => 100, 'height' => 75],
                'specifications' => ['finishing' => 'Lacquer', 'extended_length' => '240cm'],
                'is_featured' => true,
            ],

            // DINING CHAIR
            [
                'sku' => 'DCH-001',
                'name' => 'Dining Chair Scandinavian',
                'category' => 'Dining Chair',
                'short_description' => 'Kursi makan gaya Scandinavian',
                'description' => 'Kursi makan dengan desain scandinavian yang nyaman. Dudukan empuk dengan fabric premium dan kaki kayu solid.',
                'price' => 650000,
                'stock' => 50,
                'material' => 'Kayu Karet, Fabric',
                'color' => 'Grey & Natural',
                'weight' => 5.0,
                'dimensions' => ['length' => 45, 'width' => 50, 'height' => 85],
                'specifications' => ['finishing' => 'Polyester', 'bantalan' => 'High Density Foam'],
            ],
            [
                'sku' => 'DCH-002',
                'name' => 'Dining Chair Industrial',
                'category' => 'Dining Chair',
                'short_description' => 'Kursi makan bergaya industrial',
                'description' => 'Kursi makan dengan kombinasi kayu dan besi. Cocok untuk interior industrial atau rustic.',
                'price' => 550000,
                'stock' => 40,
                'material' => 'Kayu Jati, Besi',
                'color' => 'Natural & Black',
                'weight' => 6.0,
                'dimensions' => ['length' => 45, 'width' => 50, 'height' => 85],
                'specifications' => ['finishing' => 'Matte'],
            ],

            // LOUNGE CHAIR
            [
                'sku' => 'LCH-001',
                'name' => 'Lounge Chair Leather',
                'category' => 'Lounge Chair',
                'short_description' => 'Kursi santai kulit premium',
                'description' => 'Kursi santai mewah dengan lapisan kulit sintetis premium. Cocok untuk ruang baca atau sudut santai.',
                'price' => 3800000,
                'compare_price' => 4500000,
                'stock' => 10,
                'material' => 'Kayu, Kulit Sintetis',
                'color' => 'Brown Leather',
                'weight' => 25.0,
                'dimensions' => ['length' => 80, 'width' => 75, 'height' => 95],
                'specifications' => ['garansi' => '2 Tahun', 'bahan_kulit' => 'PU Leather'],
                'is_featured' => true,
            ],
            [
                'sku' => 'LCH-002',
                'name' => 'Rattan Lounge Chair',
                'category' => 'Lounge Chair',
                'short_description' => 'Kursi santai rotan natural',
                'description' => 'Kursi santai dari rotan alami yang memberikan nuansa tropis. Cocok untuk ruang tamu atau teras.',
                'price' => 2200000,
                'stock' => 15,
                'material' => 'Rotan Alami',
                'color' => 'Natural Rattan',
                'weight' => 12.0,
                'dimensions' => ['length' => 75, 'width' => 70, 'height' => 80],
                'specifications' => ['garansi' => '1 Tahun'],
                'is_featured' => true,
            ],

            // NIGHTSTAND
            [
                'sku' => 'NTS-001',
                'name' => 'Nightstand 2 Drawer',
                'category' => 'Nightstand',
                'short_description' => 'Meja samping tempat tidur 2 laci',
                'description' => 'Nakas atau meja samping tempat tidur dengan 2 laci penyimpanan. Cocok untuk menaruh lampu tidur, HP, dan buku bacaan malam.',
                'price' => 750000,
                'stock' => 30,
                'material' => 'MDF Laminate',
                'color' => 'Putih',
                'weight' => 8.0,
                'dimensions' => ['length' => 45, 'width' => 40, 'height' => 50],
                'specifications' => ['rel_laci' => 'Metal runner'],
            ],
            [
                'sku' => 'NTS-002',
                'name' => 'Nightstand Minimalist Oak',
                'category' => 'Nightstand',
                'short_description' => 'Nakas minimalis dengan finishing oak',
                'description' => 'Nakas minimalis dengan finishing oak yang elegan. Dilengkapi 1 laci dan rak terbuka.',
                'price' => 950000,
                'stock' => 20,
                'material' => 'Kayu Solid',
                'color' => 'Natural Oak',
                'weight' => 10.0,
                'dimensions' => ['length' => 50, 'width' => 40, 'height' => 55],
                'specifications' => ['finishing' => 'Clear Lacquer'],
            ],

            // DESK
            [
                'sku' => 'DSK-001',
                'name' => 'Desk WFH Adjustable',
                'category' => 'Desk',
                'short_description' => 'Meja kerja manual adjustable height',
                'description' => 'Meja kerja modern yang ketinggiannya bisa diatur (manual). Kaki besi kokoh berbentuk T. Top table luas untuk dual monitor setup.',
                'price' => 2400000,
                'stock' => 15,
                'material' => 'Besi, MDF',
                'color' => 'Hitam & Kayu',
                'weight' => 30.0,
                'dimensions' => ['length' => 140, 'width' => 70, 'height' => 75],
                'specifications' => ['height_range' => '70-110cm', 'cable_management' => 'Yes'],
            ],
            [
                'sku' => 'DSK-002',
                'name' => 'Study Desk Classic',
                'category' => 'Desk',
                'short_description' => 'Meja belajar klasik dengan laci',
                'description' => 'Meja belajar klasik dengan 3 laci penyimpanan. Cocok untuk ruang kerja atau kamar anak.',
                'price' => 1800000,
                'stock' => 20,
                'material' => 'Kayu Mahoni',
                'color' => 'Dark Walnut',
                'weight' => 35.0,
                'dimensions' => ['length' => 120, 'width' => 60, 'height' => 75],
                'specifications' => ['laci' => '3 buah'],
            ],

            // BOOKSHELF
            [
                'sku' => 'BSF-001',
                'name' => 'Bookshelf Industrial 5 Tier',
                'category' => 'Bookshelf',
                'short_description' => 'Rak buku industrial 5 tingkat',
                'description' => 'Rak buku bergaya industrial dengan 5 tingkat. Perpaduan kayu dan besi yang kokoh dan estetik.',
                'price' => 1650000,
                'stock' => 18,
                'material' => 'Kayu, Besi',
                'color' => 'Natural & Black',
                'weight' => 25.0,
                'dimensions' => ['length' => 80, 'width' => 35, 'height' => 180],
                'specifications' => ['max_load' => '50kg per tier'],
            ],
            [
                'sku' => 'BSF-002',
                'name' => 'Bookshelf Minimalist White',
                'category' => 'Bookshelf',
                'short_description' => 'Rak buku minimalis warna putih',
                'description' => 'Rak buku minimalis dengan finishing putih glossy. Cocok untuk ruang kerja atau ruang tamu modern.',
                'price' => 1200000,
                'stock' => 25,
                'material' => 'MDF Laminate',
                'color' => 'Putih Glossy',
                'weight' => 20.0,
                'dimensions' => ['length' => 80, 'width' => 30, 'height' => 160],
                'specifications' => ['rak' => '6 tingkat'],
            ],

            // BAR STOOL
            [
                'sku' => 'BST-001',
                'name' => 'Bar Stool Industrial',
                'category' => 'Bar Stool',
                'short_description' => 'Kursi bar bergaya industrial',
                'description' => 'Kursi bar tinggi dengan desain industrial. Dudukan kayu dan kaki besi adjustable.',
                'price' => 850000,
                'stock' => 30,
                'material' => 'Kayu, Besi',
                'color' => 'Natural & Black',
                'weight' => 8.0,
                'dimensions' => ['length' => 40, 'width' => 40, 'height' => 75],
                'specifications' => ['adjustable' => 'Yes', 'footrest' => 'Yes'],
            ],
            [
                'sku' => 'BST-002',
                'name' => 'Bar Stool Rattan',
                'category' => 'Bar Stool',
                'short_description' => 'Kursi bar rotan natural',
                'description' => 'Kursi bar dengan dudukan rotan yang nyaman. Memberikan nuansa tropis pada kitchen bar Anda.',
                'price' => 950000,
                'stock' => 20,
                'material' => 'Rotan, Besi',
                'color' => 'Natural Rattan',
                'weight' => 6.0,
                'dimensions' => ['length' => 45, 'width' => 45, 'height' => 75],
                'specifications' => ['footrest' => 'Yes'],
            ],

            // DRESSER & WARDROBE
            [
                'sku' => 'DRW-001',
                'name' => 'Wardrobe 3 Door Mirror',
                'category' => 'Dresser & Wardrobe',
                'short_description' => 'Lemari pakaian 3 pintu dengan cermin',
                'description' => 'Lemari pakaian luas dengan 3 pintu ayun (swing). Pintu tengah dilengkapi cermin full body. Interior lega dengan gantungan baju dan banyak rak lipat.',
                'price' => 5500000,
                'stock' => 10,
                'material' => 'MDF, Laminate oak',
                'color' => 'White Oak',
                'weight' => 95.0,
                'dimensions' => ['length' => 150, 'width' => 60, 'height' => 200],
                'specifications' => ['garansi' => '1 Tahun', 'fitur' => 'Soft close hinge'],
            ],
            [
                'sku' => 'DRW-002',
                'name' => 'Dresser 6 Drawer',
                'category' => 'Dresser & Wardrobe',
                'short_description' => 'Meja rias dengan 6 laci',
                'description' => 'Meja rias dengan 6 laci untuk menyimpan pakaian dan aksesoris. Desain minimalis modern.',
                'price' => 3200000,
                'stock' => 12,
                'material' => 'Kayu Mahoni',
                'color' => 'Natural Wood',
                'weight' => 45.0,
                'dimensions' => ['length' => 120, 'width' => 45, 'height' => 80],
                'specifications' => ['garansi' => '2 Tahun'],
            ],

            // SIDEBOARD & TV CABINET
            [
                'sku' => 'STV-001',
                'name' => 'TV Cabinet Floating',
                'category' => 'Sideboard & TV Cabinet',
                'short_description' => 'Rak TV floating/gantung untuk kesan modern',
                'description' => 'Rak TV model gantung yang hemat tempat dan membuat ruangan terasa lebih luas. Dilengkapi 3 laci penyimpanan tertutup dan area kabel yang rapi.',
                'price' => 1850000,
                'stock' => 10,
                'material' => 'Plywood HPL',
                'color' => 'Putih Glossy',
                'weight' => 18.0,
                'dimensions' => ['length' => 150, 'width' => 40, 'height' => 30],
                'specifications' => ['max_load' => '30kg', 'ukuran_tv' => 'Up to 55 inch'],
                'is_new_arrival' => true,
            ],
            [
                'sku' => 'STV-002',
                'name' => 'Sideboard Buffet Industrial',
                'category' => 'Sideboard & TV Cabinet',
                'short_description' => 'Bufet penyimpanan bergaya industrial',
                'description' => 'Bufet penyimpanan dengan perpaduan kayu dan besi. Cocok untuk ruang tamu atau ruang makan.',
                'price' => 4200000,
                'stock' => 8,
                'material' => 'Kayu Jati, Besi',
                'color' => 'Natural & Black',
                'weight' => 55.0,
                'dimensions' => ['length' => 180, 'width' => 45, 'height' => 80],
                'specifications' => ['pintu' => '3 buah', 'laci' => '2 buah'],
            ],

            // ACCESSORIES
            [
                'sku' => 'ACC-001',
                'name' => 'Set Lampu Hias Gantung',
                'category' => 'Accessories',
                'short_description' => 'Set 3 lampu gantung cafe style',
                'description' => 'Lampu gantung dekoratif berbentuk diamond dari besi. Memberikan aksen hangat dan estetik untuk ruang makan atau ruang tamu. Fitting E27 standar.',
                'price' => 650000,
                'stock' => 60,
                'material' => 'Besi',
                'color' => 'Hitam Matte',
                'weight' => 3.0,
                'dimensions' => ['length' => 25, 'width' => 25, 'height' => 30],
                'specifications' => ['isi' => '3 pcs', 'kabel' => '1 meter adjustable'],
            ],
            [
                'sku' => 'ACC-002',
                'name' => 'Set Vas Keramik Nordic',
                'category' => 'Accessories',
                'short_description' => 'Set 3 vas bunga keramik',
                'description' => 'Hiasan meja cantik berupa set 3 vas keramik dengan berbagai bentuk dan ukuran. Warna pastel yang lembut cocok untuk berbagai tema ruangan.',
                'price' => 350000,
                'stock' => 25,
                'material' => 'Keramik',
                'color' => 'Mix Pastel',
                'weight' => 2.0,
                'dimensions' => ['length' => 10, 'width' => 10, 'height' => 20],
                'specifications' => ['isi' => '3 pcs'],
            ],

            // OUTDOOR
            [
                'sku' => 'OUT-001',
                'name' => 'Set Kursi Teras Rotan',
                'category' => 'Outdoor',
                'short_description' => 'Set 2 kursi + 1 meja teras',
                'description' => 'Santai sore di teras dengan kursi rotan sintetis ini. Tahan hujan dan panas. Rangka besi anti karat. Sudah termasuk cushion duduk.',
                'price' => 2200000,
                'stock' => 10,
                'material' => 'Rotan PE, Besi',
                'color' => 'Coklat Honey',
                'weight' => 15.0,
                'dimensions' => ['length' => 60, 'width' => 60, 'height' => 80],
                'specifications' => ['tahan_cuaca' => 'Ya, Outdoor use'],
                'is_featured' => true,
            ],
            [
                'sku' => 'OUT-002',
                'name' => 'Garden Table Set Teak',
                'category' => 'Outdoor',
                'short_description' => 'Set meja taman kayu jati',
                'description' => 'Set meja dan 4 kursi taman dari kayu jati yang tahan cuaca. Cocok untuk halaman atau teras.',
                'price' => 6500000,
                'stock' => 5,
                'material' => 'Kayu Jati Solid',
                'color' => 'Natural Teak',
                'weight' => 80.0,
                'dimensions' => ['length' => 120, 'width' => 120, 'height' => 75],
                'specifications' => ['garansi' => '5 Tahun', 'kapasitas' => '4 Orang'],
                'is_featured' => true,
            ],

            // INDOOR
            [
                'sku' => 'IND-001',
                'name' => 'Indoor Plant Stand 3 Tier',
                'category' => 'Indoor',
                'short_description' => 'Rak tanaman indoor 3 tingkat',
                'description' => 'Rak tanaman untuk indoor dengan 3 tingkat. Perpaduan besi dan kayu yang estetik.',
                'price' => 450000,
                'stock' => 35,
                'material' => 'Besi, Kayu',
                'color' => 'Black & Natural',
                'weight' => 5.0,
                'dimensions' => ['length' => 50, 'width' => 25, 'height' => 80],
                'specifications' => ['max_load' => '10kg per tier'],
            ],

            // INTERIOR
            [
                'sku' => 'INT-001',
                'name' => 'Room Divider Wood Accent',
                'category' => 'Interior',
                'short_description' => 'Pembatas ruangan dengan aksen kayu',
                'description' => 'Pembatas ruangan dekoratif dengan desain geometris. Memberikan privasi sekaligus tetap terasa terbuka.',
                'price' => 2800000,
                'stock' => 8,
                'material' => 'Kayu Jati',
                'color' => 'Natural Wood',
                'weight' => 25.0,
                'dimensions' => ['length' => 180, 'width' => 3, 'height' => 180],
                'specifications' => ['panel' => '3 panel'],
            ],

            // JOGLO
            [
                'sku' => 'JGL-001',
                'name' => 'Kursi Joglo Ukir Jepara',
                'category' => 'Joglo',
                'short_description' => 'Kursi tradisional dengan ukiran Jepara',
                'description' => 'Kursi joglo dengan ukiran khas Jepara yang indah. Terbuat dari kayu jati pilihan dengan finishing natural.',
                'price' => 4500000,
                'stock' => 5,
                'material' => 'Kayu Jati Grade A',
                'color' => 'Natural Brown',
                'weight' => 35.0,
                'dimensions' => ['length' => 70, 'width' => 65, 'height' => 100],
                'specifications' => ['garansi' => '5 Tahun', 'ukiran' => 'Handmade Jepara'],
                'is_featured' => true,
            ],
            [
                'sku' => 'JGL-002',
                'name' => 'Meja Joglo Tradisional',
                'category' => 'Joglo',
                'short_description' => 'Meja tradisional gaya joglo',
                'description' => 'Meja bergaya tradisional Jawa dengan ukiran khas. Cocok untuk pendopo atau ruang tamu bergaya etnik.',
                'price' => 6800000,
                'stock' => 3,
                'material' => 'Kayu Jati Solid',
                'color' => 'Dark Teak',
                'weight' => 65.0,
                'dimensions' => ['length' => 150, 'width' => 80, 'height' => 45],
                'specifications' => ['garansi' => '5 Tahun', 'ukiran' => 'Traditional Javanese'],
            ],
        ];
    }
}
