<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends Factory<Category>
 */
class CategoryFactory extends Factory
{
    protected $model = Category::class;

    /**
     * Kategori furniture dalam Bahasa Indonesia.
     *
     * @var array<int, string>
     */
    private array $furnitureCategories = [
        'Sofa & Kursi',
        'Meja',
        'Lemari & Rak',
        'Tempat Tidur',
        'Meja Makan',
        'Kursi Makan',
        'Meja Kerja',
        'Kursi Kantor',
        'Rak Buku',
        'Meja TV',
        'Nakas',
        'Bufet',
    ];

    public function definition(): array
    {
        $name = $this->faker->unique()->randomElement($this->furnitureCategories);

        return [
            'parent_id' => null,
            'name' => $name,
            'slug' => null, // Will be auto-generated by model boot
            'description' => $this->faker->paragraph(),
            'image_path' => null,
            'sort_order' => $this->faker->numberBetween(1, 100),
            'is_active' => true,
            'is_featured' => $this->faker->boolean(30),
            'meta_title' => $name.' - Toko Furniture',
            'meta_description' => 'Koleksi '.$name.' berkualitas dengan harga terjangkau.',
        ];
    }

    /**
     * Kategori tidak aktif.
     */
    public function inactive(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_active' => false,
        ]);
    }

    /**
     * Kategori featured.
     */
    public function featured(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_featured' => true,
        ]);
    }

    /**
     * Subcategory dengan parent.
     */
    public function child(Category $parent): static
    {
        return $this->state(fn (array $attributes) => [
            'parent_id' => $parent->id,
        ]);
    }
}
