<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\ProductStatus;
use App\Enums\SaleType;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends Factory<Product>
 */
class ProductFactory extends Factory
{
    protected $model = Product::class;

    /** @var array<int, string> */
    private array $furnitureNames = [
        'Sofa Minimalis Modern',
        'Kursi Tamu Kayu Jati',
        'Meja Makan 6 Kursi',
        'Lemari Pakaian 3 Pintu',
        'Tempat Tidur King Size',
        'Meja Kerja Minimalis',
        'Rak Buku Dinding',
        'Meja TV Kayu',
        'Nakas Samping Tempat Tidur',
        'Bufet Ruang Tamu',
        'Kursi Kantor Ergonomis',
        'Meja Belajar Anak',
    ];

    /** @var array<int, string> */
    private array $materials = ['Kayu Jati', 'Kayu Mahoni', 'MDF', 'Plywood', 'Rotan', 'Besi'];

    /** @var array<int, string> */
    private array $colors = ['Coklat Tua', 'Coklat Muda', 'Hitam', 'Putih', 'Natural', 'Abu-abu'];

    public function definition(): array
    {
        $name = $this->faker->randomElement($this->furnitureNames).' '.$this->faker->word();
        $price = $this->faker->numberBetween(500000, 15000000);
        $hasDiscount = $this->faker->boolean(30);

        return [
            'category_id' => Category::factory(),
            'sku' => strtoupper(Str::random(3)).'-'.$this->faker->unique()->numerify('####'),
            'name' => $name,
            'slug' => null, // Will be auto-generated by model boot
            'short_description' => $this->faker->sentence(10),
            'description' => $this->faker->paragraphs(3, true),
            'price' => $price,
            'compare_price' => $hasDiscount ? (int) ($price * 1.2) : null,
            'cost_price' => (int) ($price * 0.6),
            'stock_quantity' => $this->faker->numberBetween(0, 100),
            'low_stock_threshold' => 5,
            'track_stock' => true,
            'allow_backorder' => false,
            'weight' => $this->faker->randomFloat(2, 5, 100),
            'length' => $this->faker->randomFloat(2, 50, 300),
            'width' => $this->faker->randomFloat(2, 30, 200),
            'height' => $this->faker->randomFloat(2, 30, 200),
            'material' => $this->faker->randomElement($this->materials),
            'color' => $this->faker->randomElement($this->colors),
            'specifications' => [
                'garansi' => $this->faker->randomElement(['1 Tahun', '2 Tahun', '3 Tahun']),
                'berat_maksimal' => $this->faker->numberBetween(50, 200).' kg',
            ],
            'status' => ProductStatus::ACTIVE,
            'sale_type' => SaleType::REGULAR,
            'is_featured' => $this->faker->boolean(20),
            'is_new_arrival' => $this->faker->boolean(30),
            'discount_percentage' => $hasDiscount ? $this->faker->randomElement([10, 15, 20, 25, 30]) : null,
            'discount_starts_at' => $hasDiscount ? now() : null,
            'discount_ends_at' => $hasDiscount ? now()->addDays(30) : null,
            'meta_title' => $name,
            'meta_description' => 'Beli '.$name.' berkualitas dengan harga terbaik.',
            'view_count' => $this->faker->numberBetween(0, 1000),
            'sold_count' => $this->faker->numberBetween(0, 100),
            'average_rating' => $this->faker->randomFloat(2, 3.5, 5),
            'review_count' => $this->faker->numberBetween(0, 50),
        ];
    }

    public function active(): static
    {
        return $this->state(fn () => ['status' => ProductStatus::ACTIVE]);
    }

    public function draft(): static
    {
        return $this->state(fn () => ['status' => ProductStatus::DRAFT]);
    }

    public function outOfStock(): static
    {
        return $this->state(fn () => [
            'status' => ProductStatus::OUT_OF_STOCK,
            'stock_quantity' => 0,
        ]);
    }

    public function featured(): static
    {
        return $this->state(fn () => ['is_featured' => true]);
    }

    public function onSale(int $percentage = 20): static
    {
        return $this->state(fn () => [
            'sale_type' => SaleType::CLEARANCE,
            'discount_percentage' => $percentage,
            'discount_starts_at' => now(),
            'discount_ends_at' => now()->addDays(30),
        ]);
    }

    public function hotSale(): static
    {
        return $this->state(fn () => ['sale_type' => SaleType::HOT_SALE]);
    }
}
